php:
  preset: laravel

  enabled:
    - length_ordered_imports
    - alpha_ordered_imports

  disabled:
    - unused_use

  finder:
    exclude:
      - "tests"
      - "node_modules"
      - "storage"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"

js: true
css: true
