services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workspace
    ports:
      - "8000:80" # Laravel
      - "5173:5173" # Vite
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
