version: 2.1
jobs:
  build:
    machine:
      image: ami-0453ec754f44f9a4a  # Use a Linux machine instead of Docker
    steps:
      - checkout
      - run:
          name: Update System and Install PHP Extensions
          command: |
            sudo apt-get update && sudo apt-get install -y zip unzip php-cli php-mbstring php-xml php-bcmath php-zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Dependencies
          command: |
            composer install --no-dev --optimize-autoloader
      - run:
          name: Run Tests
          command: |
            php artisan test

workflows:
  version: 2
  build_only:
    jobs:
      - build
