version: 2.1
jobs:
  build:
    machine:
      image: ami-0453ec754f44f9a4a  # Custom AMI ID
    steps:
      - checkout
      - run:
          name: Check PHP Version
          command: php -v
      - run:
          name: Update System and Install PHP Extensions
          command: |
            sudo apt-get update && sudo apt-get install -y zip unzip php-cli php-mbstring php-xml php-bcmath php-zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Dependencies with Verbosity
          command: |
            composer install --no-dev --optimize-autoloader -vvv
      - run:
          name: Run Tests
          command: |
            php artisan test

workflows:
  version: 2
  build_only:
    jobs:
      - build
