version: 2.1
jobs:
  build:
    machine:
      image: al2023-ami-2023.6.20241121.0-kernel-6.1-x86_64  # Use a Linux machine instead of Docker
    steps:
      - checkout
      - run:
          name: Update System and Install PHP Extensions
          command: |
            sudo apt-get update && sudo apt-get install -y zip unzip php-cli php-mbstring php-xml php-bcmath php-zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Dependencies
          command: |
            composer install --no-dev --optimize-autoloader
      - run:
          name: Run Tests
          command: |
            php artisan test

  deploy:
    machine:
      image: ubuntu-2004:2023.08.1
    steps:
      - run:
          name: Deploy Application
          command: |
            scp -r ./ ec2-user@98.81.168.142:/var/www/html/laravel
            ssh ec2-user@98.81.168.142 <<'EOF'
              cd /var/www/html/laravel
              composer install --no-dev --optimize-autoloader
              php artisan key:generate
              php artisan migrate --force
              sudo chown -R apache:apache /var/www/html/laravel
              sudo chmod -R 775 storage bootstrap/cache
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
