version: 2.1
jobs:
  build:
    machine:
      image: amazon/amazon-linux-2-x86_64  # Official Amazon Linux 2 Image
    steps:
      - checkout
      - run:
          name: Check PHP Version
          command: php -v
      - run:
          name: Install Dependencies
          command: |
            sudo yum update -y
            sudo yum install -y php-cli php-mbstring php-xml php-bcmath php-zip
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install --no-dev --optimize-autoloader
      - run:
          name: Run Tests
          command: php artisan test

workflows:
  version: 2
  build_only:
    jobs:
      - build
