name: Debug Vite Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Add PHP setup step before Node.js setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: composer:v2
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install PHP dependencies
        timeout-minutes: 10
        run: |
          echo "PHP Version: $(php -v)"
          echo "Composer Version: $(composer -V)"
          echo "Memory Limit: $(php -r 'echo ini_get("memory_limit");')"
          echo "Installing Composer dependencies..."
          
          # Try with increased memory limit
          php -d memory_limit=-1 $(which composer) install --prefer-dist --no-interaction --no-progress
          
          # Verify composer installation completed successfully
          if [ $? -eq 0 ]; then
            echo "✅ Composer install completed successfully"
          else
            echo "❌ Composer install failed"
            exit 1
          fi
          
      - name: Install Node.js Dependencies
        run: npm ci
        
      - name: Debug Environment
        run: |
          php --version
          node --version
          npm --version
          ls -la
          cat package.json
          
      - name: Build Assets
        run: |
          npm run build
          echo "Checking build output:"
          ls -la public/build/
          
          # Check .vite subdirectory where manifest is actually located
          echo "Checking .vite subdirectory:"
          ls -la public/build/.vite/
          
      - name: Verify Manifest
        run: |
          # Check for manifest in the .vite subdirectory where Vite v6+ places it
          if [ -f "public/build/.vite/manifest.json" ]; then
            echo "✅ manifest.json exists in .vite subdirectory!"
            cat public/build/.vite/manifest.json
            
            # Copy manifest to parent directory if needed by your application
            echo "Copying manifest to parent directory for compatibility"
            cp public/build/.vite/manifest.json public/build/manifest.json
          else
            echo "❌ ERROR: manifest.json not found in .vite subdirectory!"
            echo "Directory contents:"
            find public -type f | sort
            exit 1
          fi
