name: Debug Vite Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Debug Environment
        run: |
          node --version
          npm --version
          ls -la
          cat package.json
          
      - name: Build Assets
        run: |
          npm run build
          echo "Checking build output:"
          ls -la public/build/
          
          # Check .vite subdirectory where manifest is actually located
          echo "Checking .vite subdirectory:"
          ls -la public/build/.vite/
          
      - name: Verify Manifest
        run: |
          # Check for manifest in the .vite subdirectory where Vite v6+ places it
          if [ -f "public/build/.vite/manifest.json" ]; then
            echo "✅ manifest.json exists in .vite subdirectory!"
            cat public/build/.vite/manifest.json
            
            # Copy manifest to parent directory if needed by your application
            echo "Copying manifest to parent directory for compatibility"
            cp public/build/.vite/manifest.json public/build/manifest.json
          else
            echo "❌ ERROR: manifest.json not found in .vite subdirectory!"
            echo "Directory contents:"
            find public -type f | sort
            exit 1
          fi
